apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: cardis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      initContainers:
        - name: create-mlflow-bucket
          image: minio/mc:latest
          envFrom:
            - secretRef:
                name: cardis-secrets
          command:
            - sh
            - -c
            - |
              until mc alias set minio http://minio.cardis.svc.cluster.local:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY; do
                echo "Esperando MinIO..."; sleep 3
              done
              mc mb --ignore-existing minio/cardis-mlflow
      containers:
        - name: mlflow
          image: cardis/mlflow:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: cardis-secrets
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio.cardis.svc.cluster.local:9000"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
  namespace: cardis
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: cardis
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
